title: Ruo Zhang's Homepage
page-top-title: Ruo Zhang
top-section-bg-text: Reach for the stars 
home-subtitle: Ruo Zhang&ensp;|&ensp;张若
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
